ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS username CITEXT UNIQUE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN full_name DROP NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN default_currency SET DEFAULT 'ARS';
ALTER TABLE IF EXISTS users ALTER COLUMN timezone SET DEFAULT 'America/Argentina/Buenos_Aires';

CREATE TABLE IF NOT EXISTS sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
